//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public int MaBangGia { get; set; }
        public Nullable<int> GiaVN_EmBe { get; set; }
        public Nullable<int> GiaVN_TreEm { get; set; }
        public Nullable<int> GiaVN_NguoiLon { get; set; }
        public Nullable<int> GiaVK_EmBe { get; set; }
        public Nullable<int> GiaVK_TreEm { get; set; }
        public Nullable<int> GiaVK_NguoiLon { get; set; }
        public Nullable<int> GiaNQ_EmBe { get; set; }
        public Nullable<int> GiaNQ_TreEm { get; set; }
        public Nullable<int> GiaNQ_NguoiLon { get; set; }
        public Nullable<int> MaTour { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
