//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Blog_ID { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string Link_Image { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public string TacGia { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
