//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNgay
    {
        public int MaNgay { get; set; }
        public string NoiDung { get; set; }
        public int MaChiTietTour { get; set; }
        public string GioHoatDong { get; set; }
    
        public virtual Ngay Ngay { get; set; }
    }
}
