//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuTour
    {
        public int MaDichVuTour { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<int> MaChiTietTour { get; set; }
    
        public virtual ChiTietTour ChiTietTour { get; set; }
    }
}
