//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatTour
    {
        public int MaPhieuDat { get; set; }
        public Nullable<int> MaChiTietTK { get; set; }
        public Nullable<int> MaTour { get; set; }
    
        public virtual ChiTietTK ChiTietTK { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
