//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.BangGias = new HashSet<BangGia>();
            this.DanhGias = new HashSet<DanhGia>();
            this.PhieuDatTours = new HashSet<PhieuDatTour>();
            this.DiaDanhs = new HashSet<DiaDanh>();
        }
    
        public int MaTour { get; set; }
        public string TenTour { get; set; }
        public string Mota { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> MaDiaDanh { get; set; }
        public Nullable<int> MaChiTietTour { get; set; }
        public Nullable<int> NumView { get; set; }
        public string LinkImage { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> NumDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangGia> BangGias { get; set; }
        public virtual ChiTietTour ChiTietTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DiaDanh DiaDanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDatTour> PhieuDatTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaDanh> DiaDanhs { get; set; }
    }
}
